apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: rolesum
spec:
  shortDescription: Summarize RBAC roles for subjects
  homepage: https://github.com/Ladicle/kubectl-rolesum
  version: {{ .TagName }}
  platforms:
    - {{addURIAndSha "https://github.com/Ladicle/kubectl-rolesum/releases/download/{{ .TagName }}/kubectl-rolesum_linux-amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-rolesum
      files:
        - from: ./kubectl-rolesum_linux-amd64/kubectl-rolesum
          to: "."
        - from: ./kubectl-rolesum_linux-amd64/LICENSE
          to: "."
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - {{addURIAndSha "https://github.com/Ladicle/kubectl-rolesum/releases/download/{{ .TagName }}/kubectl-rolesum_linux-arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-rolesum
      files:
        - from: ./kubectl-rolesum_linux-arm64/kubectl-rolesum
          to: "."
        - from: ./kubectl-rolesum_linux-arm64/LICENSE
          to: "."
      selector:
        matchLabels:
          os: linux
          arch: arm64
    - {{addURIAndSha "https://github.com/Ladicle/kubectl-rolesum/releases/download/{{ .TagName }}/kubectl-rolesum_darwin-amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-rolesum
      files:
        - from: ./kubectl-rolesum_darwin-amd64/kubectl-rolesum
          to: "."
        - from: ./kubectl-rolesum_darwin-amd64/LICENSE
          to: "."
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - {{addURIAndSha "https://github.com/Ladicle/kubectl-rolesum/releases/download/{{ .TagName }}/kubectl-rolesum_darwin-arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-rolesum
      files:
        - from: ./kubectl-rolesum_darwin-arm64/kubectl-rolesum
          to: "."
        - from: ./kubectl-rolesum_darwin-arm64/LICENSE
          to: "."
      selector:
        matchLabels:
          os: darwin
          arch: arm64
    - {{addURIAndSha "https://github.com/Ladicle/kubectl-rolesum/releases/download/{{ .TagName }}/kubectl-rolesum_windows-amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-rolesum.exe
      files:
        - from: ./kubectl-rolesum_windows-amd64/kubectl-rolesum.exe
          to: "."
        - from: ./kubectl-rolesum_windows-amd64/LICENSE
          to: "."
      selector:
        matchLabels:
          os: windows
          arch: amd64
  description: |
    Summarize RBAC roles for subjects

    This plugin displays a graphical summary of Kubernetes RBAC roles for a given
    subject. You can easily grasp the whole picture of the roles bound to the subject.
    Available subjects are ServiceAccount, User or Group.

    Examples:
      # Summarize roles bound to the "ci-bot" ServiceAccount.
      kubectl rolesum ci-bot

      # Summarize roles bound to the "developer" Group.
      kubectl rolesum -k Group developer
